Plumbox Launcher and CLI
oogway/plumboxlauncher pull request #4
Opened 2018-02-15 06:20 UTC by Talina06

2018-02-15 10:25 UTC, meson10 requested changes

2018-02-15 10:25 UTC, meson10 commented on src/main/java/in/oogway/plumbox/cli/Localstorage.java
> +    YamlHandler yamlHandler = YamlHandler.createYamlHandler();
The format is JSON now right? It cannot be YAML. If the Local implementation is not used, please delete it.

2018-02-15 10:25 UTC, meson10 commented on src/main/java/in/oogway/plumbox/cli/Plumbox.java
> +            this.storageDriver = new Localstorage();
LocalStorage stores as YAML whereas Redis sores JSON. Keep them as same or drop the one that is not being used.

2018-02-15 10:25 UTC, meson10 commented on src/main/resources/input_source_file.json
> +[{"busID":1,"boxID":1,"latitude":18.531806,"longitude":73.850043,"timestamp":1516749989},{"busID":1,"boxID":1,"latitude":18.541184,"longitude":73.826923,"timestamp":1516748789},{"busID":1,"boxID":1,"
This should be in src/test and not in main.

2018-02-15 10:25 UTC, meson10 commented on src/main/java/in/oogway/plumbox/launcher/transformer/Transformer.java
> +    Dataset<Row> run(Dataset<Row> events);
rows and not events.

2018-02-15 10:25 UTC, meson10 commented on src/main/resources/input_source_file.json
> +[{"busID":1,"boxID":1,"latitude":18.531806,"longitude":73.850043,"timestamp":1516749989},{"busID":1,"boxID":1,"latitude":18.541184,"longitude":73.826923,"timestamp":1516748789},{"busID":1,"boxID":1,"
Also, this doesn't belong to this project.

2018-02-15 10:25 UTC, meson10 commented on src/main/java/in/oogway/plumbox/launcher/storage/RedisStorage.java
> +        Config.jedis = new Jedis(address);
Not sure if this deserves to go to Config. It should be a static/private singleton.

2018-02-15 10:25 UTC, meson10 commented on src/main/java/in/oogway/plumbox/launcher/storage/JSONParser.java
> +public interface JSONParser extends RedisStorage{
JSONParser is too ambiguous a name.

2018-02-15 10:25 UTC, meson10 commented on src/main/java/in/oogway/plumbox/launcher/storage/JSONParser.java
> +        Reader fileReader = getFileReader(bytes);
I am not sure if converting to file and loading is the best way to load content from JSON.

2018-02-15 10:25 UTC, meson10 commented on src/main/java/in/oogway/plumbox/launcher/source/Source.java
> +public class Source implements JSONParser{
Use some generic here. implements JSONParser < KnownSourceSchema >

2018-02-20 08:49 UTC, Talina06 commented
Work_branch already merged.

2018-02-20 08:49 UTC, closed without merging